---
title: "R data packages"
---

**Last updated:** `r Sys.Date()`

**Code version:** `r system("git log -1 --format='%H'", intern = TRUE)`

-----

### Background

This site list mostly single-cell RNA-seq data sets downloaded from GEO. We store each of the data sets in `ExpressionSet` object and make the data available as an R package on GitHub. 

* [Data description](data-description.html) 


### Single cell RNA-Seq Data packages

* Human
    * Tung et al., 2016, Human iPSC, UMI [GitHub](https://github.com/jhsiao999/singleCellRNASeqHumanTungiPSC); [Codes](HumanTungiPSC.html)  
      `devtools::install_github("jhsiao999/singleCellRNASeqHumanTungiPSC")`  
      
    * Leng et al., 2015, Human ESC, reads [GitHub](https://github.com/jhsiao999/singleCellRNASeqHumanLengESC); [Codes](HumanLengESC.html)  
      `devtools::install_github("jhsiao999/singleCellRNASeqHumanLengESC")`  
      
    * Patel et al., 2014 (GSE57872), Human Glioblastoma [GitHub](https://github.com/jhsiao999/singleCellRNASeqHumanPatelGlioblastoma); [Codes](HumanPatelGlioblastoma.html)  
      `devtools::install_github("jhsiao999/singleCellRNASeqHumanPatelGlioblastoma")`  
      
    * Paul et al., 2015 (GSE72850), Human Myeloid
    [GitHub](https://github.com/jhsiao999/singleCellRNASeqHumanPaulMyeloid); [Codes](HumanPaulMyeloid.html)  
      `devtools::install_github("jhsiao999/singleCellRNASeqHumanPaulMyeloid")`  
      
* Mouse
    * Buettner et al., 2015, mouse ESC, reads [GitHub](https://github.com/jhsiao999/singleCellRNASeqMouseBuettnerESC); [Codes](MouseBuettnerESC.html)  
      `devtools::install_github("jhsiao999/singleCellRNASeqMouseBuettnerESC")`  
    
    * Deng et al., 2014, mouse ESC [GitHub](https://github.com/jhsiao999/singleCellRNASeqMouseDengESC)  
      `devtools::install_github("jhsiao999/singleCellRNASeqMouseDengESC")`  
      
    * Jaitin et al., 2014, mouse Spleen cells, UMI [GitHub](https://github.com/jhsiao999/singleCellRNASeqMouseJaitinSpleen); [Codes](MouseJaitinSpleen.html)  
      `devtools::install_github("jhsiao999/singleCellRNASeqMouseJaitinSpleen")`  
      
    * Treutlein et al., 2014, mouse lung cells, reads [GitHub](https://github.com/jhsiao999/singleCellRNASeqMouseTreutleinLung); [Codes](MouseTreutleinLung.html)  
      `devtools::install_github("jhsiao999/singleCellRNASeqMouseTreutleinLung")`  
    
    * Scialdone et al., 2015, mouse liver cells [GitHub](https://github.com/jhsiao999/singleCellRNASeqMouseScialdoneLiver); [Codes](MouseScialdoneLiver.html)  
      `devtools::install_github("jhsiao999/singleCellRNASeqMouseScialdoneLiver")`  
      
    * Zeisel et al., 2015, mouse brain, UMI
      [GitHub](https://github.com/jhsiao999/singleCellRNASeqMouseZeiselBrain); [Codes](MouseZeiselBrain.html)  
      `devtools::install_github("jhsiao999/singleCellRNASeqMouseZeiselBrain")`  



### bulk sample RNA-Seq Data packages

* Mouse
    * Scialdone et al., 2015, mouse ESC [GitHub](https://github.com/jhsiao999/bulkRNASeqMouseScialdoneESC); [Codes](MouseScialdoneESC.html)  
      `devtools::install_github("jhsiao999/bulkRNASeqMouseScialdoneESC")`  



### Other related information

* [How to make SummarizedExperiment object](summarized-experiment.html)
