---
title: "Making MouseDengESC package (GSE45719)"
output:
  html_document:
    css: floating-toc.css
    toc: true
---

**Last updated:** `r Sys.Date()`

**Code version:** `r system("git log -1 --format='%H'", intern = TRUE)`

---

```{r, include = FALSE}
library(knitr)
opts_chunk$set(eval = FALSE, echo = TRUE)
```


### Load packages

```{r}
library(data.table)
library(Biobase)
```


### Make data package

Use conquer data for now.

```{r, eval = F}
#----- GSE data 
counts <- read.table('../data/MouseDengESC/Deng_cell_data.txt', 
                    skip = 2, header = FALSE, stringsAsFactors = FALSE)
geneNames <- counts[,1]
counts <- counts[,-1]

header <- as.character(unlist(read.table('../data/MouseDengESC/Deng_cell_data.txt',
                                          nrows = 1, header = FALSE)))

# make phenoData object
col_data <- data.frame(
  sample_id = paste0("cell","_",c(1:length(header))),
  cell_type = header)
rownames(col_data) <- col_data$sample_id

# make featureData object
row_data <- data.frame(geneName = geneNames,
                       stringsAsFactors = FALSE)
rownames(row_data) <- row_data$geneName

colnames(counts) <- col_data$sample_id
rownames(counts) <- row_data$geneName
# make metadata list
meta_list <- data.frame(labelDescription = c("sample ID",
                                             "embryo type"),
                        row.names = colnames(col_data))

eset_gse <- new("ExpressionSet",
            exprs = as.matrix(counts),
            phenoData = new("AnnotatedDataFrame",
                            data = col_data),
            featureData = new("AnnotatedDataFrame",
                              data = row_data),
            experimentData = new("MIAME",
                                 title = "Deng 2014 Mouse ESC (downloded from GEO)"))

#--- load the conquer-curated data
library("MultiAssayExperiment")
library("SummarizedExperiment")
conquer <- readRDS(file = "../data/MouseDengESC/conquer-GSE45719.rds")

# extract gene-level data
cts <- SummarizedExperiment::assays(experiments(conquer)[["gene"]])[["count"]]
pheno <- pData(conquer)[["source_name_ch1"]]
gene_name <- unlist(lapply(sapply(rownames(cts), function(x) strsplit(x, ".", fixed = TRUE)), "[[", 1))

cell_id <- paste0("cell.", c(1: length(pheno)))
col_data <- data.frame(cell_id = cell_id,
                       cell_type = pheno, 
                       row.names = cell_id)

row_data <- data.frame(gene_name = gene_name,
                       row.names = gene_name)
rownames(cts) <- row_data$gene_name
colnames(cts) <- col_data$cell_id

library(Biobase)
conquer_eset <- new("ExpressionSet",
            exprs = as.matrix(cts),
            phenoData = new("AnnotatedDataFrame",
                            data = col_data),
            featureData = new("AnnotatedDataFrame",
                              data = row_data),
            experimentData = new("MIAME",
                                 title = "Deng 2014 Mouse ESC (downloded from Conquer)"))

save(conquer_eset, 
        file = "../data/all-rda/MouseDengESC.rda")
```



### Session information

```{r}
sessionInfo()
```

