---
title: "Making MouseJaitinSpleen package"
author: "Joyce Hsiao"
date: "2016-08-26"
output:
  html_document:
    css: floating-toc.css
    toc: true
---


```{r, include = FALSE}
library(knitr)
opts_chunk$set(eval = FALSE, echo = TRUE)
```

### Load packages

```{r}
library(data.table)
library(Biobase)
```


### Jaitin et al., 2014, mouse spleen cells, counts + UMI


```{r, eval = FALSE}
# import count matrix, convert to a matrix object
counts <- as.matrix(
    read.table("../data/MouseJaitinSpleen/GSE54006_umitab.txt",
               header = TRUE, stringsAsFactors = FALSE,
               sep = "\t") )
gene_names <- counts[ ,1]
sample_names <- colnames(counts)[-1]
counts <- counts[ ,-1]
counts <- matrix(as.numeric(counts), byrow = FALSE,
                 nrow = length(gene_names))
rownames(counts) <- gene_names

# feature information
row_data <- data.frame(gene_names = gene_names)

# import annotation matrix
col_data <- read.table("../data/MouseJaitinSpleen/GSE54006_experimental_design.txt",
               header = TRUE,
               stringsAsFactors = FALSE,
               sep = "\t")
colnames(col_data) <- unlist(col_data[6,])
col_data <- col_data[ - c(1:6), ]
head(col_data)


# match annotation matrix with the count matrix
temp_colnames <- do.call(c,
        lapply(sample_names, function(x) strsplit(x, "X")[[1]][[2]]) )
col_data <- col_data[which(col_data$Column_name_in_processed_data_file %in%
                         temp_colnames), ]
col_data <- data.frame(col_data)

meta_list <- data.frame(row.names = colnames(col_data))

# putting all together
MouseJaitinSpleen <- new("ExpressionSet",
                exprs = as.matrix(counts),
                phenoData = new("AnnotatedDataFrame",
                                data = col_data,
                                varMetadata = meta_list),
                featureData = new("AnnotatedDataFrame",
                                  data = row_data),
                experimentData = new("MIAME",
                                     title = "Jaitin Mouse Spleen"))

save(MouseJaitinSpleen,
        file = "../data/all-rds/MouseJaitinSpleen.rda")
```



### Session information

```{r, echo = FALSE}
sessionInfo()
```

